# -*- coding: utf-8 -*-
# Baza 100 przepisow zgodnych z dieta:
# - z nabialem, bez cebuli i czosnku, bez ostrych przypraw
# - bez warzyw wzdymajacych (kalafior, brokul, kapusta, fasola, groch, cebula, czosnek)
# - bez owocow drazniacych (truskawki, maliny, kiwi, cytrusy, ananas)
# - mieso: indyk, cielecina, krolik, kurczak, chuda wolowina
# - ryby: losos, dorsz, pstrag, sandacz, mintaj, morszczuk (BEZ tunczyka)
# meals: s1=pierwsze sniadanie, s2=drugie sniadanie, ob=obiad, pw=podwieczorek, ko=kolacja
# al (alergeny): gluten, mleko, jaja, ryby, orzechy

R = [
# ---------------- PIERWSZE SNIADANIE ----------------
{"t":"Owsianka na mleku z gruszką","m":["s1","s2"],"c":"Śniadania","al":["gluten","mleko","orzechy"],"kcal":480,
 "ing":[("płatki owsiane","60 g"),("mleko","250 ml"),("gruszka","150 g"),("masło migdałowe","10 g"),("cynamon","szczypta")],
 "steps":["Płatki zalej mlekiem, gotuj na małym ogniu 5–7 min, mieszając.","Dodaj startą lub pieczoną gruszkę, masło migdałowe i cynamon."]},
{"t":"Owsianka na mleku z bananem","m":["s1","s2"],"c":"Śniadania","al":["gluten","mleko","orzechy"],"kcal":470,
 "ing":[("płatki owsiane","60 g"),("mleko","250 ml"),("banan","120 g"),("masło migdałowe","10 g")],
 "steps":["Płatki zalej mlekiem, gotuj 5–7 min do kremowej konsystencji.","Dodaj pokrojonego banana i masło migdałowe."]},
{"t":"Owsianka na mleku z borówkami","m":["s1","s2"],"c":"Śniadania","al":["gluten","mleko"],"kcal":460,
 "ing":[("płatki owsiane","60 g"),("mleko","250 ml"),("borówki","80 g"),("miód","1 łyżeczka")],
 "steps":["Ugotuj płatki na mleku (5–7 min).","Wyłóż borówki i skrop odrobiną miodu."]},
{"t":"Owsianka z pieczonym jabłkiem i cynamonem","m":["s1"],"c":"Śniadania","al":["gluten","mleko"],"kcal":470,
 "ing":[("płatki owsiane","60 g"),("mleko","250 ml"),("jabłko","150 g"),("cynamon","1/2 łyżeczki")],
 "steps":["Jabłko pokrój, uduś z cynamonem na patelni z odrobiną wody (6–8 min).","Ugotuj płatki na mleku i połącz z jabłkiem."]},
{"t":"Jaglanka na mleku z jabłkiem","m":["s1"],"c":"Śniadania","al":["mleko"],"kcal":490,
 "ing":[("kasza jaglana","60 g"),("mleko","250 ml"),("jabłko","150 g"),("cynamon","szczypta")],
 "steps":["Kaszę przepłucz gorącą wodą, ugotuj na mleku (15 min pod przykryciem).","Dodaj duszone z cynamonem jabłko."]},
{"t":"Jaglanka z gruszką i borówkami","m":["s1"],"c":"Śniadania","al":["mleko"],"kcal":500,
 "ing":[("kasza jaglana","60 g"),("mleko","250 ml"),("gruszka","120 g"),("borówki","60 g")],
 "steps":["Ugotuj jaglankę na mleku (15 min).","Wyłóż pokrojoną gruszkę i borówki."]},
{"t":"Kasza manna na mleku z borówkami","m":["s1"],"c":"Śniadania","al":["gluten","mleko"],"kcal":430,
 "ing":[("kasza manna","50 g"),("mleko","300 ml"),("borówki","70 g")],
 "steps":["Zagotuj mleko, wsyp mannę cienkim strumieniem, mieszaj 2–3 min.","Wyłóż borówki na wierzch."]},
{"t":"Ryż na mleku z jabłkiem i cynamonem","m":["s1"],"c":"Śniadania","al":["mleko"],"kcal":470,
 "ing":[("ryż","60 g"),("mleko","300 ml"),("jabłko","150 g"),("cynamon","1/2 łyżeczki")],
 "steps":["Ryż ugotuj na mleku na małym ogniu (ok. 20 min).","Dodaj starte jabłko i cynamon."]},
{"t":"Jajecznica na maśle z koperkiem","m":["s1"],"c":"Śniadania","al":["jaja","mleko","gluten"],"kcal":400,
 "ing":[("jajka","3 szt."),("masło","10 g"),("koperek","1 łyżka"),("pieczywo orkiszowe","2 kromki")],
 "steps":["Rozpuść masło na małym ogniu, wbij jajka, mieszaj do ścięcia (2–3 min).","Posyp koperkiem, podawaj z pieczywem."]},
{"t":"Jajka na miękko z pieczywem","m":["s1"],"c":"Śniadania","al":["jaja","gluten","mleko"],"kcal":340,
 "ing":[("jajka","2 szt."),("pieczywo orkiszowe","2 kromki"),("masło","10 g")],
 "steps":["Gotuj jajka we wrzątku 4 min.","Podawaj z pieczywem posmarowanym masłem."]},
{"t":"Omlet z cukinią","m":["s1"],"c":"Śniadania","al":["jaja","mleko"],"kcal":360,
 "ing":[("jajka","3 szt."),("cukinia","100 g"),("masło","10 g")],
 "steps":["Cukinię zetrzyj, podsmaż chwilę na maśle.","Zalej roztrzepanymi jajkami, smaż pod przykryciem 4–5 min."]},
{"t":"Omlet na słodko z jabłkiem","m":["s1"],"c":"Śniadania","al":["jaja","mleko"],"kcal":380,
 "ing":[("jajka","3 szt."),("jabłko","120 g"),("mleko","30 ml"),("masło","10 g")],
 "steps":["Jabłko uduś na maśle.","Roztrzep jajka z mlekiem, wlej na patelnię, smaż i przełóż jabłkiem."]},
{"t":"Twarożek z koperkiem i pieczywem","m":["s1","s2"],"c":"Nabiał","al":["mleko","gluten"],"kcal":350,
 "ing":[("twaróg półtłusty","150 g"),("jogurt naturalny","2 łyżki"),("koperek","1 łyżka"),("ogórek","60 g"),("pieczywo orkiszowe","2 kromki")],
 "steps":["Twaróg rozgnieć z jogurtem i koperkiem.","Podawaj z pieczywem i plasterkami ogórka."]},
{"t":"Placuszki owsiane na maślance z jabłkiem","m":["s1"],"c":"Śniadania","al":["gluten","mleko","jaja"],"kcal":520,
 "ing":[("płatki owsiane","60 g"),("maślanka","100 ml"),("jajko","1 szt."),("jabłko","120 g"),("masło","10 g")],
 "steps":["Wymieszaj płatki, maślankę, jajko i starte jabłko, odstaw 10 min.","Smaż małe placuszki na maśle po 2–3 min z każdej strony."]},
{"t":"Kasza jaglana zapiekana z gruszką","m":["s1"],"c":"Śniadania","al":["mleko"],"kcal":480,
 "ing":[("kasza jaglana","60 g"),("mleko","250 ml"),("gruszka","150 g")],
 "steps":["Ugotuj jaglankę na mleku.","Przełóż do naczynia z gruszką i zapiecz 12 min w 180°C."]},
{"t":"Owsianka z brzoskwinią","m":["s1","s2"],"c":"Śniadania","al":["gluten","mleko"],"kcal":460,
 "ing":[("płatki owsiane","60 g"),("mleko","250 ml"),("brzoskwinia","120 g")],
 "steps":["Ugotuj płatki na mleku.","Dodaj pokrojoną brzoskwinię."]},
{"t":"Budyń jaglany waniliowy z borówkami","m":["s1","pw"],"c":"Śniadania","al":["mleko"],"kcal":420,
 "ing":[("kasza jaglana","60 g"),("mleko","250 ml"),("wanilia","szczypta"),("borówki","60 g")],
 "steps":["Ugotuj jaglankę na mleku z wanilią, zblenduj na gładko.","Wyłóż borówki, podawaj ciepłe lub schłodzone."]},
{"t":"Grzanki z twarożkiem i borówkami","m":["s1","s2"],"c":"Nabiał","al":["gluten","mleko"],"kcal":360,
 "ing":[("pieczywo orkiszowe","2 kromki"),("twaróg półtłusty","120 g"),("borówki","50 g")],
 "steps":["Pieczywo podpiecz na złoto.","Posmaruj twarogiem i wyłóż borówki."]},
{"t":"Kanapki z serem żółtym łagodnym","m":["s1","s2"],"c":"Kanapki","al":["gluten","mleko"],"kcal":400,
 "ing":[("pieczywo orkiszowe","2 kromki"),("ser żółty łagodny","60 g"),("ogórek","60 g"),("masło","5 g")],
 "steps":["Pieczywo posmaruj masłem.","Ułóż ser i plasterki ogórka."]},
{"t":"Ryżanka z jabłkiem","m":["s1","s2"],"c":"Śniadania","al":["mleko"],"kcal":400,
 "ing":[("ryż","50 g"),("mleko","300 ml"),("jabłko","120 g"),("cynamon","szczypta")],
 "steps":["Ugotuj ryż na mleku.","Dodaj starte jabłko i cynamon."]},

# ---------------- DRUGIE SNIADANIE ----------------
{"t":"Jogurt naturalny z borówkami i owsem","m":["s2","pw"],"c":"Nabiał","al":["mleko","gluten"],"kcal":260,
 "ing":[("jogurt naturalny","200 g"),("borówki","70 g"),("płatki owsiane","20 g")],
 "steps":["Jogurt przełóż do miski.","Dodaj borówki i płatki owsiane."]},
{"t":"Jogurt z bananem i owsem","m":["s2","pw"],"c":"Nabiał","al":["mleko","gluten"],"kcal":280,
 "ing":[("jogurt naturalny","200 g"),("banan","100 g"),("płatki owsiane","20 g")],
 "steps":["Jogurt wymieszaj z pokrojonym bananem.","Posyp płatkami owsianymi."]},
{"t":"Kefir z bananem","m":["s2","pw"],"c":"Nabiał","al":["mleko"],"kcal":230,
 "ing":[("kefir","250 ml"),("banan","100 g")],
 "steps":["Kefir zblenduj z bananem lub podawaj z pokrojonym bananem obok."]},
{"t":"Maślanka z gruszką","m":["s2","pw"],"c":"Nabiał","al":["mleko"],"kcal":220,
 "ing":[("maślanka","250 ml"),("gruszka","120 g")],
 "steps":["Podawaj maślankę z pokrojoną gruszką lub zblenduj razem."]},
{"t":"Serek wiejski z ogórkiem","m":["s2"],"c":"Nabiał","al":["mleko"],"kcal":240,
 "ing":[("serek wiejski","150 g"),("ogórek","70 g"),("koperek","1 łyżka")],
 "steps":["Serek wymieszaj z koperkiem.","Dodaj pokrojony ogórek."]},
{"t":"Twarożek na słodko z bananem","m":["s2","pw"],"c":"Nabiał","al":["mleko"],"kcal":320,
 "ing":[("twaróg półtłusty","150 g"),("jogurt naturalny","2 łyżki"),("banan","100 g")],
 "steps":["Twaróg rozgnieć z jogurtem.","Dodaj pokrojonego banana."]},
{"t":"Kanapki z pastą jajeczną","m":["s2"],"c":"Kanapki","al":["gluten","jaja","mleko"],"kcal":420,
 "ing":[("pieczywo orkiszowe","2 kromki"),("jajka","2 szt."),("jogurt naturalny","1 łyżka"),("koperek","1 łyżka")],
 "steps":["Jajka ugotuj na twardo, posiekaj i wymieszaj z jogurtem i koperkiem.","Nałóż pastę na pieczywo."]},
{"t":"Kanapki z pastą z pieczonego indyka","m":["s2"],"c":"Kanapki","al":["gluten","mleko"],"kcal":430,
 "ing":[("pieczywo orkiszowe","2 kromki"),("indyk","80 g"),("jogurt naturalny","1 łyżka"),("ogórek","50 g")],
 "steps":["Pieczonego indyka drobno posiekaj i wymieszaj z jogurtem.","Nałóż na pieczywo, dodaj ogórek."]},
{"t":"Kanapki z twarogiem i borówkami","m":["s2"],"c":"Kanapki","al":["gluten","mleko"],"kcal":380,
 "ing":[("pieczywo orkiszowe","2 kromki"),("twaróg półtłusty","120 g"),("borówki","50 g")],
 "steps":["Posmaruj pieczywo twarogiem.","Wyłóż borówki."]},
{"t":"Sałatka owocowa z jogurtem","m":["s2","pw"],"c":"Owoce i desery","al":["mleko"],"kcal":260,
 "ing":[("jabłko","80 g"),("gruszka","80 g"),("banan","80 g"),("jogurt naturalny","100 g")],
 "steps":["Owoce pokrój w kostkę.","Zalej jogurtem i wymieszaj."]},
{"t":"Koktajl bananowy na kefirze","m":["s2","pw"],"c":"Nabiał","al":["mleko"],"kcal":250,
 "ing":[("kefir","250 ml"),("banan","120 g")],
 "steps":["Zblenduj kefir z bananem na gładki koktajl."]},
{"t":"Koktajl jagodowy na jogurcie","m":["s2","pw"],"c":"Nabiał","al":["mleko"],"kcal":240,
 "ing":[("jogurt naturalny","200 g"),("borówki","80 g"),("banan","80 g")],
 "steps":["Zblenduj jogurt z borówkami i bananem."]},
{"t":"Placki z cukinii pieczone","m":["s2"],"c":"Śniadania","al":["jaja","gluten","mleko"],"kcal":360,
 "ing":[("cukinia","150 g"),("jajko","1 szt."),("mąka orkiszowa","3 łyżki"),("ser żółty łagodny","30 g")],
 "steps":["Cukinię zetrzyj, odciśnij, wymieszaj z jajkiem, mąką i serem.","Piecz placki w 190°C ok. 15 min."]},
{"t":"Racuchy z jabłkiem na jogurcie","m":["s2"],"c":"Śniadania","al":["gluten","mleko","jaja"],"kcal":480,
 "ing":[("mąka orkiszowa","80 g"),("jogurt naturalny","100 g"),("jajko","1 szt."),("jabłko","120 g"),("masło","10 g")],
 "steps":["Wymieszaj mąkę, jogurt, jajko i starte jabłko.","Smaż racuchy na maśle po 2–3 min z każdej strony."]},
{"t":"Jogurt z pieczonym jabłkiem i cynamonem","m":["s2","pw"],"c":"Nabiał","al":["mleko"],"kcal":250,
 "ing":[("jogurt naturalny","200 g"),("jabłko","120 g"),("cynamon","szczypta")],
 "steps":["Jabłko upiecz z cynamonem.","Dodaj do jogurtu."]},
{"t":"Muffiny owsiano-bananowe","m":["s2","pw"],"c":"Śniadania","al":["gluten","mleko","jaja"],"kcal":300,
 "ing":[("płatki owsiane","60 g"),("banan","100 g"),("jajko","1 szt."),("jogurt naturalny","50 g")],
 "steps":["Zmiksuj płatki, banana, jajko i jogurt.","Piecz w foremkach 20 min w 180°C."]},
{"t":"Kanapki z pieczonym indykiem i sałatą","m":["s1","s2","ko"],"c":"Kanapki","al":["gluten"],"kcal":420,
 "ing":[("pieczywo orkiszowe","2 kromki"),("indyk","80 g"),("sałata","20 g"),("ogórek","50 g")],
 "steps":["Upiecz pierś indyka i pokrój w plastry.","Złóż kanapki z sałatą, indykiem i ogórkiem."]},
{"t":"Twaróg z brzoskwinią","m":["s2","pw"],"c":"Nabiał","al":["mleko"],"kcal":300,
 "ing":[("twaróg półtłusty","150 g"),("jogurt naturalny","2 łyżki"),("brzoskwinia","120 g")],
 "steps":["Twaróg rozgnieć z jogurtem.","Dodaj pokrojoną brzoskwinię."]},
{"t":"Grzanki z serem i pieczoną cukinią","m":["s2"],"c":"Kanapki","al":["gluten","mleko"],"kcal":390,
 "ing":[("pieczywo orkiszowe","2 kromki"),("ser żółty łagodny","50 g"),("cukinia","80 g")],
 "steps":["Cukinię podpiecz na patelni.","Ułóż na pieczywie z serem i zapiecz 5 min."]},

# ---------------- OBIAD ----------------
{"t":"Pieczona pierś z indyka z ziemniakami","m":["ob"],"c":"Mięso","al":[],"kcal":560,
 "ing":[("indyk","180 g"),("ziemniaki","250 g"),("marchew","100 g"),("oliwa","1 łyżka"),("majeranek","szczypta")],
 "steps":["Pierś natrzyj oliwą, solą i majerankiem.","Piecz z ziemniakami i marchewką 30 min w 190°C."]},
{"t":"Indyk duszony w sosie koperkowym z ryżem","m":["ob"],"c":"Mięso","al":["mleko"],"kcal":580,
 "ing":[("indyk","180 g"),("ryż","60 g"),("jogurt naturalny","2 łyżki"),("koperek","1 łyżka")],
 "steps":["Indyka pokrój, obsmaż i duś z wodą 15 min.","Wmieszaj jogurt i koperek, podawaj z ryżem."]},
{"t":"Pulpeciki z indyka w sosie własnym","m":["ob"],"c":"Mięso","al":[],"kcal":560,
 "ing":[("indyk mielony","150 g"),("ryż","40 g"),("marchew","80 g"),("koperek","1 łyżka")],
 "steps":["Mięso wymieszaj z ugotowanym ryżem i startą marchwią, uformuj pulpeciki.","Duś w wodzie 15 min, posyp koperkiem."]},
{"t":"Kotleciki mielone z indyka z puree","m":["ob"],"c":"Mięso","al":["gluten","mleko","jaja"],"kcal":620,
 "ing":[("indyk mielony","150 g"),("bułka tarta","2 łyżki"),("jajko","1 szt."),("ziemniaki","250 g"),("mleko","40 ml"),("masło","10 g")],
 "steps":["Z mięsa, bułki i jajka uformuj kotleciki, usmaż lub upiecz.","Ziemniaki ugnieć z mlekiem i masłem na puree."]},
{"t":"Gulasz z indyka z cukinią i kaszą gryczaną","m":["ob"],"c":"Mięso","al":[],"kcal":590,
 "ing":[("indyk","160 g"),("cukinia","100 g"),("marchew","80 g"),("kasza gryczana","60 g")],
 "steps":["Indyka obsmaż, duś 20 min, dodaj cukinię i marchew, duś 10 min.","Podawaj z ugotowaną kaszą gryczaną."]},
{"t":"Cielęcina duszona z marchewką i puree","m":["ob"],"c":"Mięso","al":["mleko"],"kcal":620,
 "ing":[("cielęcina","180 g"),("marchew","100 g"),("ziemniaki","250 g"),("mleko","40 ml"),("masło","10 g")],
 "steps":["Cielęcinę obsmaż i duś 35 min, dodaj marchew, duś 10 min.","Ziemniaki ugnieć z mlekiem i masłem."]},
{"t":"Gulasz z cielęciny z kaszą gryczaną","m":["ob"],"c":"Mięso","al":["gluten"],"kcal":640,
 "ing":[("cielęcina","180 g"),("marchew","80 g"),("pietruszka","50 g"),("kasza gryczana","60 g"),("mąka orkiszowa","1 łyżeczka")],
 "steps":["Mięso obsmaż, duś 40 min, dodaj warzywa, duś 15 min.","Sos zagęść mąką, podawaj z kaszą."]},
{"t":"Pulpety cielęce w sosie koperkowym","m":["ob"],"c":"Mięso","al":["mleko"],"kcal":600,
 "ing":[("cielęcina mielona","150 g"),("ryż","40 g"),("jogurt naturalny","2 łyżki"),("koperek","1 łyżka"),("ziemniaki","200 g")],
 "steps":["Z mięsa i ryżu uformuj pulpety, duś 15 min.","Wmieszaj jogurt i koperek, podawaj z ziemniakami."]},
{"t":"Sznycel cielęcy z ziemniakami i buraczkami","m":["ob"],"c":"Mięso","al":["gluten","jaja"],"kcal":650,
 "ing":[("cielęcina","150 g"),("jajko","1 szt."),("bułka tarta","3 łyżki"),("ziemniaki","250 g"),("buraki","100 g")],
 "steps":["Cielęcinę rozbij, panieruj w jajku i bułce, usmaż na złoto.","Podawaj z ziemniakami i tartymi buraczkami."]},
{"t":"Duszony królik w sosie własnym z kaszą","m":["ob"],"c":"Mięso","al":[],"kcal":600,
 "ing":[("królik","180 g"),("marchew","80 g"),("pietruszka","50 g"),("kasza gryczana","60 g"),("liść laurowy","1 szt.")],
 "steps":["Królika obsmaż, duś 45 min z liściem laurowym.","Dodaj warzywa, duś 15 min, podawaj z kaszą."]},
{"t":"Królik pieczony z ziemniakami i marchewką","m":["ob"],"c":"Mięso","al":["mleko"],"kcal":640,
 "ing":[("królik","180 g"),("ziemniaki","250 g"),("marchew","100 g"),("masło","10 g"),("tymianek","szczypta")],
 "steps":["Króliki natrzyj masłem i tymiankiem, ułóż z warzywami.","Piecz pod przykryciem 40 min, potem 15 min bez."]},
{"t":"Królik duszony w warzywach z ryżem","m":["ob"],"c":"Mięso","al":[],"kcal":610,
 "ing":[("królik","180 g"),("marchew","80 g"),("cukinia","80 g"),("ryż","60 g")],
 "steps":["Królika obsmaż, duś 45 min.","Dodaj marchew i cukinię, duś 15 min, podawaj z ryżem."]},
{"t":"Pieczony kurczak z ziemniakami","m":["ob"],"c":"Mięso","al":[],"kcal":600,
 "ing":[("kurczak","200 g"),("ziemniaki","250 g"),("marchew","80 g"),("oliwa","1 łyżka"),("majeranek","szczypta")],
 "steps":["Kurczaka natrzyj oliwą i majerankiem.","Piecz z ziemniakami i marchewką 40 min w 190°C."]},
{"t":"Rosół z kurczaka z makaronem","m":["ob"],"c":"Zupy","al":["gluten"],"kcal":380,
 "ing":[("kurczak","150 g"),("marchew","80 g"),("pietruszka","50 g"),("makaron","50 g"),("lubczyk","szczypta")],
 "steps":["Kurczaka i warzywa gotuj 40 min (bez cebuli), dopraw lubczykiem.","Podawaj z ugotowanym makaronem."]},
{"t":"Kurczak duszony w sosie z marchewką i ryżem","m":["ob"],"c":"Mięso","al":["mleko"],"kcal":560,
 "ing":[("kurczak","180 g"),("marchew","100 g"),("ryż","60 g"),("jogurt naturalny","2 łyżki")],
 "steps":["Kurczaka obsmaż, duś z marchewką 20 min.","Wmieszaj jogurt, podawaj z ryżem."]},
{"t":"Klopsiki z kurczaka w sosie koperkowym","m":["ob"],"c":"Mięso","al":["mleko"],"kcal":560,
 "ing":[("kurczak mielony","150 g"),("kasza jaglana","50 g"),("jogurt naturalny","2 łyżki"),("koperek","1 łyżka")],
 "steps":["Z mięsa uformuj klopsiki, duś 15 min.","Dodaj jogurt i koperek, podawaj z kaszą jaglaną."]},
{"t":"Gulasz z chudej wołowiny z kaszą","m":["ob"],"c":"Mięso","al":["gluten"],"kcal":650,
 "ing":[("chuda wołowina","180 g"),("marchew","80 g"),("pietruszka","50 g"),("kasza gryczana","60 g"),("mąka orkiszowa","1 łyżeczka")],
 "steps":["Wołowinę obsmaż, duś 40 min, dodaj warzywa, duś 15 min.","Sos zagęść mąką, podawaj z kaszą."]},
{"t":"Duszona wołowina z puree i buraczkami","m":["ob"],"c":"Mięso","al":["mleko"],"kcal":660,
 "ing":[("chuda wołowina","180 g"),("ziemniaki","250 g"),("mleko","40 ml"),("masło","10 g"),("buraki","100 g")],
 "steps":["Wołowinę duś do miękkości (ok. 50 min).","Podawaj z puree i tartymi buraczkami."]},
{"t":"Pieczony łosoś z batatami i cukinią","m":["ob","ko"],"c":"Ryby","al":["ryby"],"kcal":660,
 "ing":[("łosoś","180 g"),("batat","200 g"),("cukinia","100 g"),("oliwa","1 łyżka"),("koperek","1 łyżka")],
 "steps":["Batata i cukinię piecz 10 min, dołóż łososia.","Piecz razem 15 min w 190°C, posyp koperkiem."]},
{"t":"Dorsz pieczony z ziemniakami i marchewką","m":["ob","ko"],"c":"Ryby","al":["ryby"],"kcal":520,
 "ing":[("dorsz","200 g"),("ziemniaki","250 g"),("marchew","80 g"),("oliwa","1 łyżka")],
 "steps":["Dorsza skrop oliwą i posól.","Piecz z ziemniakami i marchewką 20 min w 190°C."]},
{"t":"Dorsz duszony z warzywami i ryżem","m":["ob","ko"],"c":"Ryby","al":["ryby","mleko"],"kcal":560,
 "ing":[("dorsz","200 g"),("marchew","80 g"),("cukinia","80 g"),("ryż","60 g"),("masło","10 g")],
 "steps":["Warzywa duś na maśle 8 min.","Ułóż dorsza, duś 8–10 min, podawaj z ryżem."]},
{"t":"Pstrąg pieczony z ziemniakami i koperkiem","m":["ob","ko"],"c":"Ryby","al":["ryby"],"kcal":600,
 "ing":[("pstrąg","180 g"),("ziemniaki","250 g"),("koperek","1 łyżka"),("oliwa","1 łyżka")],
 "steps":["Ziemniaki podgotuj, ułóż z pstrągiem na blaszce.","Skrop oliwą, posyp koperkiem, piecz 20 min w 190°C."]},
{"t":"Sandacz pieczony z puree i cukinią","m":["ob","ko"],"c":"Ryby","al":["ryby","mleko"],"kcal":580,
 "ing":[("sandacz","180 g"),("ziemniaki","250 g"),("mleko","40 ml"),("masło","10 g"),("cukinia","80 g")],
 "steps":["Sandacza i cukinię upiecz 15 min w 190°C.","Ziemniaki ugnieć z mlekiem i masłem."]},
{"t":"Mintaj duszony w warzywach z ryżem","m":["ob","ko"],"c":"Ryby","al":["ryby"],"kcal":500,
 "ing":[("mintaj","200 g"),("marchew","80 g"),("cukinia","80 g"),("ryż","60 g")],
 "steps":["Warzywa duś 8 min, ułóż mintaja, duś 8 min.","Podawaj z ryżem."]},
{"t":"Morszczuk pieczony z batatami","m":["ob","ko"],"c":"Ryby","al":["ryby"],"kcal":540,
 "ing":[("morszczuk","200 g"),("batat","200 g"),("cukinia","80 g"),("oliwa","1 łyżka")],
 "steps":["Batata piecz 10 min, dołóż morszczuka i cukinię.","Piecz razem 15 min w 190°C."]},
{"t":"Risotto z indykiem i cukinią","m":["ob","ko"],"c":"Mięso","al":["mleko"],"kcal":630,
 "ing":[("indyk","150 g"),("ryż","80 g"),("cukinia","100 g"),("marchew","60 g"),("masło","10 g"),("ser żółty łagodny","20 g")],
 "steps":["Indyka obsmaż, odłóż. Podsmaż warzywa, dodaj ryż.","Wlewaj bulion po chochelce (18 min), dodaj mięso, masło i ser."]},
{"t":"Risotto z cielęciną i marchewką","m":["ob","ko"],"c":"Mięso","al":["mleko"],"kcal":640,
 "ing":[("cielęcina","150 g"),("ryż","80 g"),("marchew","80 g"),("masło","10 g"),("ser żółty łagodny","20 g")],
 "steps":["Cielęcinę obsmaż, odłóż. Podsmaż marchew, dodaj ryż.","Dolewaj bulion (18 min), na końcu mięso, masło i ser."]},
{"t":"Zapiekana cukinia z indykiem i ziemniakami","m":["ob"],"c":"Mięso","al":["mleko"],"kcal":600,
 "ing":[("indyk","150 g"),("cukinia","150 g"),("ziemniaki","200 g"),("ser żółty łagodny","30 g")],
 "steps":["Warstwowo ułóż plastry ziemniaka, cukinii i indyka.","Posyp serem, zapiekaj 35 min w 190°C."]},
{"t":"Kasza gryczana z marchewką i kurczakiem","m":["ob"],"c":"Kasze i dodatki","al":[],"kcal":560,
 "ing":[("kurczak","150 g"),("kasza gryczana","70 g"),("marchew","100 g"),("oliwa","1 łyżka")],
 "steps":["Kurczaka pokrój i obsmaż, dodaj marchew, duś 12 min.","Podawaj z ugotowaną kaszą gryczaną."]},
{"t":"Leniwe pierogi z twarogu","m":["ob"],"c":"Nabiał","al":["mleko","jaja","gluten"],"kcal":520,
 "ing":[("twaróg półtłusty","150 g"),("jajko","1 szt."),("mąka orkiszowa","60 g"),("masło","10 g")],
 "steps":["Twaróg zmiel, wymieszaj z jajkiem i mąką, uformuj wałek, pokrój.","Gotuj 3 min, polej roztopionym masłem."]},
{"t":"Makaron z kurczakiem i cukinią","m":["ob"],"c":"Mięso","al":["gluten","mleko"],"kcal":620,
 "ing":[("makaron","70 g"),("kurczak","150 g"),("cukinia","100 g"),("jogurt naturalny","2 łyżki")],
 "steps":["Kurczaka i cukinię podsmaż, wmieszaj jogurt.","Połącz z ugotowanym makaronem."]},
{"t":"Pieczony indyk z batatami i szpinakiem","m":["ob"],"c":"Mięso","al":[],"kcal":580,
 "ing":[("indyk","180 g"),("batat","200 g"),("szpinak","80 g"),("oliwa","1 łyżka")],
 "steps":["Indyka i batata piecz 30 min w 190°C.","Szpinak podduś na oliwie i podawaj obok."]},
{"t":"Pulpety z indyka z marchewką i ryżem","m":["ob"],"c":"Mięso","al":[],"kcal":580,
 "ing":[("indyk mielony","150 g"),("ryż","60 g"),("marchew","100 g")],
 "steps":["Z mięsa i części ryżu uformuj pulpety, duś 15 min z marchewką.","Podawaj z ugotowanym ryżem."]},
{"t":"Cielęcina pieczona z ziemniakami i cukinią","m":["ob"],"c":"Mięso","al":[],"kcal":620,
 "ing":[("cielęcina","180 g"),("ziemniaki","250 g"),("cukinia","100 g"),("oliwa","1 łyżka"),("majeranek","szczypta")],
 "steps":["Cielęcinę natrzyj oliwą i majerankiem.","Piecz z ziemniakami i cukinią 35 min w 190°C."]},

# ---------------- PODWIECZOREK ----------------
{"t":"Pieczone jabłko z cynamonem","m":["pw"],"c":"Owoce i desery","al":[],"kcal":140,
 "ing":[("jabłko","150 g"),("cynamon","szczypta")],
 "steps":["Jabłko wydrąż, posyp cynamonem.","Piecz 15–18 min w 180°C."]},
{"t":"Pieczona gruszka z cynamonem","m":["pw"],"c":"Owoce i desery","al":[],"kcal":140,
 "ing":[("gruszka","150 g"),("cynamon","szczypta")],
 "steps":["Gruszkę przekrój, posyp cynamonem.","Piecz 15 min w 180°C."]},
{"t":"Pieczone jabłko z borówkami","m":["pw"],"c":"Owoce i desery","al":[],"kcal":160,
 "ing":[("jabłko","150 g"),("borówki","40 g"),("cynamon","szczypta")],
 "steps":["Jabłko wydrąż, wypełnij borówkami, posyp cynamonem.","Piecz 15–18 min w 180°C."]},
{"t":"Twaróg z gruszką","m":["pw"],"c":"Nabiał","al":["mleko"],"kcal":300,
 "ing":[("twaróg półtłusty","150 g"),("jogurt naturalny","2 łyżki"),("gruszka","120 g")],
 "steps":["Twaróg rozgnieć z jogurtem.","Dodaj pokrojoną gruszkę."]},
{"t":"Kisiel borówkowy","m":["pw"],"c":"Owoce i desery","al":[],"kcal":150,
 "ing":[("borówki","100 g"),("mąka ziemniaczana","1 łyżka"),("woda","200 ml")],
 "steps":["Zagotuj borówki z wodą.","Zagęść mąką rozrobioną w zimnej wodzie, zagotuj."]},
{"t":"Budyń waniliowy na mleku","m":["pw"],"c":"Nabiał","al":["mleko"],"kcal":220,
 "ing":[("mleko","250 ml"),("mąka kukurydziana","2 łyżki"),("wanilia","szczypta")],
 "steps":["Rozprowadź mąkę w części mleka.","Zagotuj resztę mleka z wanilią, wlej zawiesinę, mieszaj do zgęstnienia."]},
{"t":"Ryżanka z borówkami","m":["pw"],"c":"Nabiał","al":["mleko"],"kcal":300,
 "ing":[("ryż","50 g"),("mleko","250 ml"),("borówki","60 g")],
 "steps":["Ryż ugotuj na mleku.","Dodaj borówki."]},
{"t":"Mus z pieczonych jabłek","m":["pw"],"c":"Owoce i desery","al":[],"kcal":130,
 "ing":[("jabłko","200 g"),("cynamon","szczypta")],
 "steps":["Jabłka upiecz z cynamonem.","Zblenduj lub rozgnieć widelcem na mus."]},
{"t":"Banan pieczony z cynamonem","m":["pw"],"c":"Owoce i desery","al":[],"kcal":160,
 "ing":[("banan","120 g"),("cynamon","szczypta")],
 "steps":["Banana naciśnij wzdłuż, posyp cynamonem.","Piecz 12 min w 180°C."]},
{"t":"Koktajl gruszkowy na kefirze","m":["pw"],"c":"Nabiał","al":["mleko"],"kcal":230,
 "ing":[("kefir","250 ml"),("gruszka","120 g")],
 "steps":["Zblenduj kefir z gruszką."]},
{"t":"Placuszki bananowe","m":["pw"],"c":"Owoce i desery","al":["jaja","gluten"],"kcal":280,
 "ing":[("banan","100 g"),("jajko","1 szt."),("płatki owsiane","30 g")],
 "steps":["Banana rozgnieć, wymieszaj z jajkiem i płatkami.","Smaż małe placuszki po 2 min z każdej strony."]},
{"t":"Sałatka z jabłka i gruszki z jogurtem","m":["pw"],"c":"Owoce i desery","al":["mleko"],"kcal":220,
 "ing":[("jabłko","100 g"),("gruszka","100 g"),("jogurt naturalny","100 g")],
 "steps":["Owoce pokrój w kostkę.","Zalej jogurtem."]},
{"t":"Grzanki z masłem i pieczoną gruszką","m":["pw"],"c":"Owoce i desery","al":["gluten","mleko"],"kcal":260,
 "ing":[("pieczywo orkiszowe","2 kromki"),("gruszka","120 g"),("masło","5 g")],
 "steps":["Pieczywo podpiecz i posmaruj masłem.","Ułóż plasterki pieczonej gruszki."]},
{"t":"Twarożek z brzoskwinią i owsem","m":["pw"],"c":"Nabiał","al":["mleko","gluten"],"kcal":320,
 "ing":[("twaróg półtłusty","150 g"),("brzoskwinia","100 g"),("płatki owsiane","15 g")],
 "steps":["Twaróg rozgnieć, dodaj pokrojoną brzoskwinię.","Posyp płatkami owsianymi."]},
{"t":"Mus bananowo-jagodowy","m":["pw"],"c":"Owoce i desery","al":[],"kcal":150,
 "ing":[("banan","120 g"),("borówki","60 g")],
 "steps":["Zblenduj banana z borówkami na gładki mus."]},

# ---------------- KOLACJA ----------------
{"t":"Krem z dyni z grzankami","m":["ko","ob"],"c":"Zupy","al":["gluten","mleko"],"kcal":450,
 "ing":[("dynia","250 g"),("marchew","80 g"),("ziemniaki","100 g"),("masło","10 g"),("pieczywo orkiszowe","1 kromka")],
 "steps":["Warzywa podduś na maśle, zalej wodą, gotuj 20 min.","Zblenduj na krem, podawaj z grzankami."]},
{"t":"Krem z marchwi i batata","m":["ko","ob"],"c":"Zupy","al":["gluten","mleko"],"kcal":470,
 "ing":[("marchew","150 g"),("batat","150 g"),("ziemniaki","80 g"),("masło","10 g"),("pieczywo orkiszowe","1 kromka")],
 "steps":["Warzywa ugotuj do miękkości (20–25 min).","Zblenduj z masłem, podawaj z grzankami."]},
{"t":"Krem z cukinii z grzankami","m":["ko","ob"],"c":"Zupy","al":["gluten","mleko"],"kcal":400,
 "ing":[("cukinia","250 g"),("ziemniaki","100 g"),("masło","10 g"),("pieczywo orkiszowe","1 kromka")],
 "steps":["Cukinię i ziemniaki ugotuj, zblenduj z masłem.","Podawaj z grzankami."]},
{"t":"Zupa jarzynowa z indykiem","m":["ko","ob"],"c":"Zupy","al":[],"kcal":420,
 "ing":[("indyk","120 g"),("marchew","80 g"),("ziemniaki","120 g"),("cukinia","80 g"),("pietruszka","40 g")],
 "steps":["Indyka gotuj 20 min (bez cebuli).","Dodaj pokrojone warzywa, gotuj 15 min."]},
{"t":"Zupa ziemniaczana z koperkiem","m":["ko","ob"],"c":"Zupy","al":[],"kcal":380,
 "ing":[("ziemniaki","250 g"),("marchew","80 g"),("pietruszka","40 g"),("koperek","1 łyżka")],
 "steps":["Warzywa ugotuj do miękkości.","Rozgnieć częściowo, posyp koperkiem."]},
{"t":"Rosołek warzywny z ryżem","m":["ko"],"c":"Zupy","al":[],"kcal":300,
 "ing":[("marchew","80 g"),("pietruszka","40 g"),("ryż","50 g"),("lubczyk","szczypta")],
 "steps":["Warzywa gotuj 20 min, dopraw lubczykiem.","Dodaj ugotowany ryż."]},
{"t":"Jajecznica na maśle z pieczywem","m":["ko"],"c":"Śniadania","al":["jaja","mleko","gluten"],"kcal":400,
 "ing":[("jajka","3 szt."),("masło","10 g"),("pieczywo orkiszowe","2 kromki")],
 "steps":["Usmaż jajecznicę na maśle (nie przesmażaj).","Podawaj z pieczywem."]},
{"t":"Omlet z serem i cukinią","m":["ko"],"c":"Śniadania","al":["jaja","mleko"],"kcal":380,
 "ing":[("jajka","3 szt."),("ser żółty łagodny","30 g"),("cukinia","80 g"),("masło","10 g")],
 "steps":["Cukinię podsmaż na maśle.","Zalej jajkami, posyp serem, smaż pod przykryciem 5 min."]},
{"t":"Twarożek z koperkiem i pieczywem (kolacja)","m":["ko"],"c":"Nabiał","al":["mleko","gluten"],"kcal":350,
 "ing":[("twaróg półtłusty","150 g"),("koperek","1 łyżka"),("ogórek","60 g"),("pieczywo orkiszowe","2 kromki")],
 "steps":["Twaróg wymieszaj z koperkiem.","Podawaj z pieczywem i ogórkiem."]},
{"t":"Pstrąg pieczony z cukinią","m":["ko","ob"],"c":"Ryby","al":["ryby"],"kcal":600,
 "ing":[("pstrąg","180 g"),("cukinia","100 g"),("ziemniaki","200 g"),("oliwa","1 łyżka")],
 "steps":["Pstrąga, cukinię i ziemniaki ułóż na blaszce, skrop oliwą.","Piecz 20 min w 190°C."]},
{"t":"Łosoś pieczony z cukinią","m":["ko","ob"],"c":"Ryby","al":["ryby"],"kcal":520,
 "ing":[("łosoś","160 g"),("cukinia","120 g"),("oliwa","1 łyżka"),("koperek","1 łyżka")],
 "steps":["Łososia i cukinię skrop oliwą, posyp koperkiem.","Piecz 16 min w 190°C."]},
{"t":"Dorsz na parze z ziemniakami","m":["ko","ob"],"c":"Ryby","al":["ryby"],"kcal":480,
 "ing":[("dorsz","200 g"),("ziemniaki","250 g"),("koperek","1 łyżka")],
 "steps":["Dorsza gotuj na parze 10 min.","Podawaj z ziemniakami i koperkiem."]},
{"t":"Sałatka z pieczonym kurczakiem i ziemniakami","m":["ko"],"c":"Mięso","al":[],"kcal":520,
 "ing":[("kurczak","150 g"),("ziemniaki","200 g"),("sałata","20 g"),("ogórek","60 g"),("oliwa","1 łyżka")],
 "steps":["Kurczaka upiecz i pokrój.","Wymieszaj z ciepłymi ziemniakami, sałatą i ogórkiem, skrop oliwą."]},
{"t":"Kasza jaglana z duszoną cukinią i marchewką","m":["ko"],"c":"Kasze i dodatki","al":["mleko"],"kcal":420,
 "ing":[("kasza jaglana","60 g"),("cukinia","100 g"),("marchew","80 g"),("masło","10 g")],
 "steps":["Warzywa duś na maśle 8 min.","Podawaj z ugotowaną kaszą jaglaną."]},
{"t":"Puree ziemniaczane z jajkiem i buraczkami","m":["ko"],"c":"Kasze i dodatki","al":["mleko","jaja"],"kcal":480,
 "ing":[("ziemniaki","250 g"),("mleko","40 ml"),("masło","10 g"),("jajka","2 szt."),("buraki","100 g")],
 "steps":["Ziemniaki ugnieć z mlekiem i masłem.","Podawaj z jajkami na twardo i tartymi buraczkami."]},
{"t":"Kanapki z pastą jajeczną (kolacja)","m":["ko"],"c":"Kanapki","al":["gluten","jaja","mleko"],"kcal":420,
 "ing":[("pieczywo orkiszowe","2 kromki"),("jajka","2 szt."),("jogurt naturalny","1 łyżka"),("ogórek","50 g")],
 "steps":["Jajka posiekaj i wymieszaj z jogurtem.","Nałóż na pieczywo, dodaj ogórek."]},
{"t":"Zupa krem z marchwi z ryżem","m":["ko","ob"],"c":"Zupy","al":[],"kcal":360,
 "ing":[("marchew","200 g"),("ziemniaki","80 g"),("ryż","30 g"),("oliwa","1 łyżka")],
 "steps":["Marchew i ziemniaki ugotuj, zblenduj na krem.","Dodaj ugotowany ryż i łyżkę oliwy."]},
]
